### ISSUE TITLE
Clear cart on follow

### ISSUE THREAD

**Issue by jwahdatehagh** [ethereumfollowprotocol/app#95]
The cart doesn't seem to be cleared when navigating before tx is complete // even though the follows have been synced up by the efp api.

**Comment by jwahdatehagh** [comment]
<img width="1292" alt="Screenshot 2024-09-06 at 20 52 24" src="https://github.com/user-attachments/assets/6aef39c5-d269-4864-be81-c013024dae0e">

just encountered this again... (already following all the folks in my cart)

**Comment by brantlymillegan** [comment]
We've made it so people have to go all the through, should mitigate this problem
